languaje: node_js
node_js:
  - "6.4.1"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm install
  - cd functions
  - npm install
  - cd..
after_success:
  - npm run build
  - firebase deploy --only hosting --token $FIREBASE_TOKEN